---
# Univeral tasks
- name: Check for uservars file
  ansible.builtin.stat:
    path: "uservars/{{ ansible_user_id }}.yml"
  register: uservars_exists
  tags:
    - always

- name: Create uservars file if it doesn't exist
  ansible.builtin.copy:
    src: "uservars/template.yml"
    dest: "uservars/{{ ansible_user_id }}.yml"
    mode: 0644
  when: not uservars_exists.stat.exists
  tags:
    - always

- name: include_vars | Include username based vars
  ansible.builtin.include_vars:
    file: "uservars/{{ ansible_user_id }}.yml"

# Optional software roles
- include_tasks: ohmyzsh.yml
  when: ohmyzsh | bool

# User-defined software

# Advanced customization tasks

- import_tasks: template.yml

- name: file | Create user-defined directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0750
  loop: "{{ user_dir_list }}"
  when: user_dir_list is defined

- name: copy | Copy files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner|d(ansible_user_id) }}"
    group: "{{ item.group|d('staff') }}"
    mode: "{{ item.mode|d('0640') }}"
  loop: "{{ user_file_list }}"
  when: user_file_list is defined

- name: template | Template files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner|d(ansible_user_id) }}"
    group: "{{ item.group|d('staff') }}"
    mode: "{{ item.mode|d('0640') }}"
  loop: "{{ user_template_list }}"
  when: user_template_list is defined
